# Site settings
title: 快图
email: your-email@domain.com
intro: "轻如鹅毛，快如闪电，简约现代，快图浏览为您挚爱的图片提供了理想的相册。"
functions: "- 免费、干净。我们不会请求非必要的权限<br>
- 支持网盘服务 (如百度云, Picasa, Google Drive, Dropbox, Flickr, OneDrive, 500px 等)<br>
- 瞬间发现与载入上万张图片<br>
- 以最好的画质查看或放映您的照片，比其它应用更快更好!<br>
- 按时间和地理位置分组照片<br>
- 可指定仅包含或排除特定文件夹<br>
- 可以隐藏您的隐私照片和视频，并设置保护密码<br>
- 支持播放 GIF 动画和视频影像<br>
- 流畅的操作体验：滑动切换图片，双指捏合、双击后拖动缩放，双指旋转<br>
- 内置简单图片处理器，满足您对图片进行旋转，缩放，裁切等需求，亦可以将图片以最佳画质设为墙纸<br>
- 强大的文件管理能力，您可以排序、重命名、新建文件夹，移动或复制图片<br>
- 通过 WiFi 在多个设备间快传文件，无需移动数据流量<br>
- Material风格和沉浸模式"

description: "description"
# Color settings (hex-codes without the leading hash-tag)

color:
  primary: 0399fc #80B3FF
  primary-dark: 0788dd #80B3FF
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F
  
# Footer settings
footer:
  copyright: Q-Supreme team
  location: 我们在
  social: 官方圈子
  credits: Credits

# Blog category setting
blog:
    cate-filter: blog
    
# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: google
    url: https://plus.google.com/communities/108111396258376510219
  - title: weibo
    url: http://weibo.com/u/1489508705
  - title: qq
    url: 

# Postal address (add as many lines as necessary)
address:
  - line: 上海市杨浦区
  - line: 锦创路20号 602
  
# Credits content
credits: 'Freelance is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Download url
downurl:
    direct: http://alensw.com/assets/quickpic_3.9.apk
    playurl: https://play.google.com/store/apps/details?id=com.alensw.PicFolder
    play-img-url: https://dt8kf6553cww8.cloudfront.net/static/images/app_store_badges/android-google-play-en-vflL9Vk_v.png
    
playurl: https://play.google.com/store/apps/details?id=com.alensw.PicFolder

# Build settings for jekyll!!!!
paginate: 20
#paginate_path: "news/page:num"
markdown: kramdown
#permalink: pretty
permalink: /:title/